# Experimental!
~ "git: github.com/amatgil/steal-gift" ~ AoCGet
Test ← $ 3-5
       $ 10-14
       $ 16-20
       $ 12-18
       $ 
       $ 1
       $ 5
       $ 8
       $ 11
       $ 17
       $ 32

P     ← °≡⊟∩⍆⊙⋕≡◇(⊜⋕⊸≠@-)⊃↙(↘+1)⊸˜⨂□""°/$"_\n_"
Merge ← ⊓⌞▽(↘₁⊕/↥\+)≡⊢⊙≡°⊟∩⌞↯∞_2⧆₁⊸\↥♭⍉⊟ # most of p2
P₁    ← /+×=0⟜\+⊏⍏˜∩˜⊂˜∘-⟜¬◿2°⊏♭⊙⟜⧆₀⍉⊟Merge
P₂    ← +⧻⟜/+-Merge

⊃(⍤⤙≍ 14 P₂|⍤⤙≍ 3 P₁)P Test
⊃P₂P₁P AoCGet 2025 5
